apiVersion: v1
kind: Pod
metadata:
  name: lms
  labels:
    app: lms
spec:
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: lms-data-pvc
  containers:
  - name: lms
    volumeMounts:
    - mountPath: "/var/lms"
      name: pv-storage
    image: epoupon/lms
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: music-trio-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: lms
  ports:
  - port: 5082
    targetPort: 5082
    nodePort: 30000

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: lms-data-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/aaiken/docker-spotdl/lms/data/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lms-data-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
