apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-trio-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: music-trio
  replicas: 0
  template:
    metadata:
      labels:
        app: music-trio
    spec:
      containers:
      - name: lms
        image: epoupon/lms
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: music-trio-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: music-trio
  ports:
  - port: 5082
    targetPort: 5082
    nodePort: 30001

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: lms-data-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/aaiken/docker-spotdl/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lms-data-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
