apiVersion: v1
kind: Pod
metadata:
  name: filebrowser
  labels:
    app: filebrowser
spec:
  containers:
    - name: filebrowser
      image: filebrowser/filebrowser
      ports:
        - name: filebrowser-web
          containerPort: 80
          protocol: TCP
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 100m
          memory: 200Mi
      volumeMounts:
        - mountPath: "/srv"
          name: music-vault-storage
        - mountPath: "/var/lms"
          name: data-store
  volumes:
    - name: music-vault-storage
      persistentVolumeClaim:
        claimName: music-vault-pvc
    - name: data-store
      emptyDir: {}
