apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-vault-pv
spec:
  accessModes:
  - "ReadWriteOnce"
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  local:
    path: /foo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "master"