version: "3"

services:
  discord.js:
    container_name: spotdl-Sound
    image: spotdl-Sound
    build:
      context: .
    ports:
    - "8123"
    restart: unless-stopped
    environment:
      DISCORD_PREFIX: "*"
      DISCORD_TOKEN: ""
